# Generated by Django 5.1.1 on 2024-09-08 04:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks2', '0003_bookmark_delete_bookmark2'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='url',
            field=models.URLField(default='', verbose_name='URL'),
        ),
        migrations.AlterUniqueTogether(
            name='bookmark',
            unique_together={('url', 'user')},
        ),
    ]
